name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: "Force MKDocs to use stable version"
      run: pip install mkdocs==1.1.2
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
        pip install mkdocs mkdocs-material

    - name: Build and Deploy
      run: |
        mkdocs gh-deploy --force
