name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Build and Deploy
      uses: actions/jekyll-build-pages@v1
      with:
        source: './docs'
        destination: './docs/_site'
